entrypoint.sh

https://jira.jahia.org/browse/PROJECT-XXX
The following are included in this PR
I have considered the following implications of my change:

fix mariadb testdb string

---

Dockerfile
filter_graphql_update.xml

https://jira.jahia.org/browse/SAAS-32
- Configure permissions for GraphQL API

SAAS-32: Configure permissions for GraphQL API

---

Dockerfile
config_mariadb.xml
config_mariadb_v8.xml
config_postgresql.xml
config_postgresql_v8.xml

https://jira.jahia.org/browse/SAAS-35
- Install imageMagick 7

SAAS-35: Install imageMagick 7

---

.circleci/config.yml

https://jira.jahia.org/browse/PROJECT-XXX
The following are included in this PR
I have considered the following implications of my change:

SAAS-66 add a not perfect circleci plan

---

.circleci/config.yml

https://jira.jahia.org/browse/SAAS-140
The following are included in this PR
I have considered the following implications of my change:

SAAS-140 Docker public images - check by instanciating image before push

---

Dockerfile
README.md
entrypoint.sh

https://jira.jahia.org/browse/SAAS-169

SAAS-169 -- Add a parameter for logs rotations

---

entrypoint.sh

https://jira.jahia.org/browse/SAAS-182

SAAS-182: init database if empty before starting jahia

---

Dockerfile
entrypoint.sh

https://jira.jahia.org/browse/BACKLOG-14277

BACKLOG-14277 update version.txt path

---

Dockerfile

https://jira.jahia.org/browse/SAAS-192
- Fix hadolint linter warnings

SAAS-92: Fix hadolint linter warnings

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-14282

BACKLOG-14282: add jahia 8.0.1.0

---

.circleci/config.yml

As per the title, this includes the necessary configuration changes for 7.3.5.1 and 7.3.4.2

Updated config for releases 7.3.5.1 and 7.3.4.2

---

.circleci/config.yml

https://jira.jahia.org/browse/COPS-128

COPS-128: Stop using global cloud-qa context

---

.circleci/config.yml

Artifacts have been made available on download.jahia.com

Generate release 7.3.6.0

---

.circleci/.anchore/policy_bundle.json
.circleci/config.yml

https://jira.jahia.org/browse/SAAS-231
Remove on commit event anchore scan
Add new java CVE to whitelist

Saas 231 anchore scan

---

.circleci/.anchore/policy_bundle.json

https://jira.jahia.org/browse/SAAS-231

SAAS-231: Fix json typo in anchore policies

---

.circleci/config.yml

Updated config for Jahia 8.0.2.0

---

.circleci/config.yml
Dockerfile

https://jira.jahia.org/browse/SAAS-256

SAAS-256 use 'tomcat' user and group

---

.circleci/config.yml

BACKLOG-15279 - Added config for 7.3.7.0

---

.circleci/config.yml
Dockerfile

https://jira.jahia.org/browse/SAAS-261
Enable Jahia 8.0.2.0_fs for Free trial platform

SAAS-261: jahia 8.0.2

---

Dockerfile

https://jira.jahia.org/browse/SAAS-261
Fix datastore permissions in case it is not in the database

SAAS-261: fix datastore permissions

---

.circleci/config.yml

Changes in circleci to build the 7380 image

BACKLOG-15538 - PR for the 7380 docker image

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-16444
The following are included in this PR
I have considered the following implications of my change:

BACKLOG-16444: Add config for Jahia 7.3.10.0 release

---

Dockerfile

https://jira.jahia.org/browse/QA-12806
Issues when trying to build jahia 7 docker image: https://app.circleci.com/pipelines/github/Jahia/jahia-ee/4714/workflows/9636d33b-f472-4015-86ff-62dbc08b2a4d/jobs/17453
Minor fixes:
* Install missing packages `wget`, `unzip`
* Update imagemagick download url
Tested to work here: https://app.circleci.com/pipelines/github/Jahia/jahia-ee/4717/workflows/62d6a086-3787-403a-b4a2-942e901e0089/jobs/17477

QA-12806: Docker build fixes/update
